# Generated by Django 5.2.14 on 2026-05-19 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_category',
            field=models.CharField(choices=[('A', 'Мотоциклы'), ('B', 'Легковые авто'), ('C', 'Грузовые авто')], default='B', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_series',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)]),
        ),
    ]
