# Generated by Django 5.2.14 on 2026-05-06 03:53

import django.db.models.deletion
import rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[rentals.models.validate_price])),
                ('status', models.CharField(choices=[('active', 'Активна'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('end_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals_end', to='cars.location')),
                ('start_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals_start', to='cars.location')),
            ],
        ),
    ]
