# Generated by Django 5.2.14 on 2026-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='required_license',
            field=models.CharField(choices=[('A', 'Мотоциклы'), ('B', 'Легковые авто'), ('C', 'Грузовые авто')], default='B', max_length=10),
        ),
    ]
